name: checkthat-numerical
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - ipykernel
  - rerankers
  - matplotlib
  - scikit-learn
  - networkx
  - numpy==2.0
  - pandas
  - polars
  - pillow
  - pytz
  - requests
  - safetensors
  - scikit-learn
  - scipy
  - sentence-transformers
  - seaborn
  - tokenizers
  - tqdm
  - tiktoken
  - ruff
  - pip
  - pacmap
  - umap-learn
  - peft

  - pip:
    - transformers
    - torch
    - python-terrier
    - huggingface-hub
    - python-dotenv
    - openai
    - wandb
    - "rerankers[flashrank]"
    - "rerankers[rankllm]"