data:
  claims_train: "data/decomposition/train_claims_decomposed.json"
  claims_val: "data/decomposition/val_claims_decomposed.json"
  corpus: "data/corpus_evidence_unified.json"

reranking: 
  gpu: True # To use GPU for the reranking or not
  model_name: "cross-encoder/ms-marco-MiniLM-L-12-v2" #https://huggingface.co/cross-encoder
  model_type_cpu: "flashrank"  # To use for CPU inference
  model_type_gpu: "cross-encoder" # To use for GPU inference
  batch_size: 50 # GPU Only. Increase that when on PACE and using GPU (or if you have a good GPU card)
  k: 50 #How many to keep after retrieval
  clean_index: True
  wmodel: "BM25" #Retrieval model


  